/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'apple': {
          'blue': '#007AFF',
          'green': '#34C759',
          'red': '#FF3B30',
          'orange': '#FF9500',
          'yellow': '#FFCC00',
          'teal': '#5AC8FA',
          'purple': '#AF52DE',
          'pink': '#FF2D92',
          'gray': '#8E8E93',
          'gray2': '#AEAEB2',
          'gray3': '#C7C7CC',
          'gray4': '#D1D1D6',
          'gray5': '#E5E5EA',
          'gray6': '#F2F2F7',
          'bg': '#FFFFFF',
          'secondary-bg': '#F2F2F7',
          'tertiary-bg': '#FFFFFF',
          'grouped-bg': '#F2F2F7',
          'grouped-secondary-bg': '#FFFFFF',
          'text': '#1d1d1f',
          'text-secondary': '#6e6e73',
          'separator': 'rgba(60, 60, 67, 0.29)',
          'overlay': 'rgba(0, 0, 0, 0.4)',
        },
        'apple-dark': {
          'blue': '#0A84FF',
          'green': '#30D158',
          'red': '#FF453A',
          'orange': '#FF9F0A',
          'yellow': '#FFD60A',
          'teal': '#64D2FF',
          'purple': '#BF5AF2',
          'pink': '#FF375F',
          'gray': '#8E8E93',
          'gray2': '#636366',
          'gray3': '#48484A',
          'gray4': '#3A3A3C',
          'gray5': '#2C2C2E',
          'gray6': '#1C1C1E',
          'bg': '#000000',
          'secondary-bg': '#1C1C1E',
          'tertiary-bg': '#2C2C2E',
          'grouped-bg': '#1C1C1E',
          'grouped-secondary-bg': '#2C2C2E',
          'text': '#FFFFFF',
          'text-secondary': '#8E8E93',
          'separator': 'rgba(84, 84, 88, 0.65)',
          'overlay': 'rgba(0, 0, 0, 0.7)',
        },
      },
      fontFamily: {
        'apple': ['-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'Inter', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'SF Mono', 'Monaco', 'Consolas', 'monospace'],
      },
      borderRadius: {
        'apple': '18px',
        'apple-sm': '12px',
        'apple-lg': '20px',
      },
      spacing: {
        'apple': '24px',
        'apple-sm': '16px',
        'apple-lg': '32px',
      },
      boxShadow: {
        'apple': '0 4px 20px rgba(0, 0, 0, 0.08)',
        'apple-lg': '0 8px 40px rgba(0, 0, 0, 0.12)',
        'apple-hover': '0 12px 60px rgba(0, 0, 0, 0.15)',
        'apple-dark': '0 4px 20px rgba(0, 0, 0, 0.3)',
        'apple-dark-lg': '0 8px 40px rgba(0, 0, 0, 0.4)',
      },
      backdropBlur: {
        'apple': '20px',
      },
      animation: {
        'apple-fade-in': 'appleFadeIn 0.3s ease-out',
        'apple-slide-up': 'appleSlideUp 0.4s ease-out',
        'apple-scale': 'appleScale 0.2s ease-out',
        'apple-pulse': 'applePulse 2s ease-in-out infinite',
        'gradient-shift': 'gradientShift 8s ease infinite',
        'float': 'float 20s infinite linear',
        'bounce-slow': 'bounce 2s infinite',
        'spin-slow': 'spin 3s linear infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
      },
      keyframes: {
        appleFadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        appleSlideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        appleScale: {
          '0%': { transform: 'scale(0.95)' },
          '100%': { transform: 'scale(1)' },
        },
        applePulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        gradientShift: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        float: {
          '0%': { transform: 'translateY(100vh) rotate(0deg)', opacity: '0' },
          '10%': { opacity: '0.1' },
          '90%': { opacity: '0.1' },
          '100%': { transform: 'translateY(-100px) rotate(360deg)', opacity: '0' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
      },
    },
  },
  plugins: [],
}